### ISSUE TITLE
goblin 0.0.18 fails to parse dynsyms

### ISSUE THREAD

**Issue by endeav0r** [m4b/goblin#111]
I am parsing a simple binary (I have uploaded the binary here: http://reversing.io/goblin/loop-0 ).

I recently updated to goblin 0.0.18, and noticed some symbols were not being parsed. `Elf.dynsyms.len()` returns a length of zero. I ran the binary through `bingrep`, and dynsyms were parsed fine, but then noticed I was on `bingrep` `0.5.0`. I upgraded `bingrep` to the latest version, and now I get the following:

```
                 0    WEAK       NOTYPE      _ITM_registerTMCloneTable                0x0                             0x0    
                 0    WEAK       FUNC        __cxa_finalize@@GLIBC_2.2.5              0x0                             0x0    
               530    GLOBAL     FUNC        _init                                    0x0     .init(11)               0x0    

Dyn Syms(0):
  
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /Users/travis/build/rust-lang/rust/src/libcore/slice/mod.rs:2085:10
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I am troubleshooting through goblin, but thought I would share the issue now.

**Comment by endeav0r** [comment]
`gnu_hash_len` from @philipc's push here: https://github.com/m4b/goblin/commit/f682b1850ec6179c53402f58cbad8eea5acabe6d is returning `0` for this binary.

**Comment by philipc** [comment]
That binary has no defined dynamic symbols, and 7 undefined symbols.

The hash table min_chain value is 1, which means that the defined dynamic symbols start at 1. That is, after the placeholder symbol at index 0. We could potentially change `gnu_hash_len` to return `1` instead of `0` in this case, but that's not going to gain you anything IMO. I should double check that the logic in `gnu_hash_len` is correct for an empty hash table though, and that it's not reading undefined values.

What we could do is find the maximum symbol index in the dyn/plt relocations if `gnu_hash_len` returns 0.

**Comment by m4b** [comment]
I'm confused; the binary appears to have several imported symbols, which the dynamic linker would have to resolve; not finding the symbols (or returning 0, when there are 7) in this case seems like a regression, yes?

**Comment by philipc** [comment]
Yes, it's a regression, but the question is, how do you determine how many imported symbols there are? As you know, the binary does not include a length for the dynamic symbol table. AFAIK the dynamic linker accesses the imported symbols via the index in relocations, so if we want to find them then we need to do the same.

**Comment by m4b** [comment]
@endeav0r ok new version 0.0.19 published, sorry about that :/ please let us know if you see anything else, hopefully this is resolved :)

**Comment by endeav0r** [comment]
Thanks guys :) I'll give `0.0.19` a run here in the next few days.
