### ISSUE TITLE
How do I get raw data from `rodata` section of an ELF share object?

### ISSUE THREAD

**Issue by lzutao** [m4b/goblin#126]
Sorry if this issue bothers the author. I have asked this question on Rust discord channel and
still I couldn't find the answer. Could the author tell me what can I do to get raw data
from an section of an ELF share object?

**Comment by philipc** [comment]
If you only need a high level interface, consider using the [object](https://crates.io/crates/object) crate. Otherwise, it contains examples of how to do what you want:
- [get the section given the name](https://github.com/gimli-rs/object/blob/318842144e72aec72680e750a0764bb084c93171/src/elf.rs#L106-L122)
- [get the data given the section](https://github.com/gimli-rs/object/blob/318842144e72aec72680e750a0764bb084c93171/src/elf.rs#L325-L331)

**Comment by lzutao** [comment]
Thanks @philipc . I'd give object crate a try.

**Comment by Sparrownor1** [comment]
Is there a way to do this within `goblin` itself however? Would not like to use other crates if possible for the sake of uniformity

**Comment by philipc** [comment]
Those links I gave were from when `object` still depended on `goblin`. The code they contain shows how to do it using only `goblin`.
