### ISSUE TITLE
I need a little help for a simple file extract :)

### ISSUE THREAD

**Issue by cyberpunkbln** [m4b/goblin#167]
Hello,

i want only to try to extract an ico file or other binary files from an exe-file like 7zip, that can extract files from the .rsrc dir.

Great will be ifi receive an Buffer that i can furtheruse with the crate image readBuffer-Functions.

thx

ps: knows anybody if any wrapper exist for this library with standard operations like extracting ans so on?

**Comment by m4b** [comment]
Unfortunately I don’t have enough context here to help; extracting data should be straightforward since you must already have the byte buffer. For PE specific stuff I would suggest to read the PE spec or at the returned structs we provide which should be documented.

If they aren’t documented please file an issue, or bette yet file a jira. Going to close this now, thanks !
