### ISSUE TITLE
Consider releasing 0.1.0

### ISSUE THREAD

**Issue by nox** [m4b/goblin#190]
Given that not all new releases include breaking changes, it would be nice to be able to use this crate with a version number that can support non-breaking bumps. Given `0.0.x` is compatible with anything than itself, that can't be done unless this is switched to `0.x.y`.

**Comment by m4b** [comment]
Yes that seems reasonable, next version will be 0.1.0; unfortunately in process of upgrading scroll, seems that 0.10 is broken w.r.t. re-exporting derive macros, i'm not sure how it's possible :(

**Comment by m4b** [comment]
scroll 0.10.0 was broken; fixed (and yanked); published goblin `0.1.0` :)

**Comment by andrewshadura** [comment]
Thanks! I just wanted to make sure you know about these issues:
1) The dotnet example doesn’t work in the published crate because of the dll asset missing (not sure if it is *actually* missing or is that the Debian tooling mangling it)
2) Somehow during the Debian build the parse_self test cannot find the "self" and fails.

**Comment by andrewshadura** [comment]
Btw, I know it probably would sound a bit pedantic for you, but could you publish the source for the dll asset?

**Comment by andrewshadura** [comment]
(I’m just thinking I can probably replace that asset with any .net binary from a random Debian mono package.)
