### ISSUE TITLE
Panic in  src/archive/mode.rs:163

### ISSUE THREAD

**Issue by anfedotoff** [m4b/goblin#328]
Hi!
We were doing some fuzzing with libFuzzer and our tool Sydr and we found some issues. Here is the panic message:
`thread 'main' panicked at 'byte index 3 is not a char boundary; it is inside 'Г' (bytes 2..4) of `00Г00`', library/core/src/str/mod.rs:127:5`. The problem is because we try to build utf-8 str from non-utf8 characters [here](https://github.com/m4b/goblin/blob/master/src/archive/mod.rs#L112). The obvious  fix is to use: 
```rust
std::str::from_utf8(&buffer[header_offset..header_offset+SIZEOF_FILE_IDENTIFER])?
```

But goblin is std-free. Do you have any ideas?
Btw, we use goblin in our tools (sydr-fuzz, casr). It is very nice crate:).

**Comment by m4b** [comment]
Thanks for fuzzing, I love that!

I’m a bit busy but I’ll begin triage on issues little later this week, however for particular case of from_utf8 this is available in core: https://doc.rust-lang.org/stable/core/str/fn.from_utf8.html

so that should allow your suggested fix to work in no std environment :)

**Comment by anfedotoff** [comment]
Well, I Iooked. This [function](https://github.com/rust-lang/rust/blob/master/library/core/src/str/validations.rs#L127) does validation of utf8 strings in std. We could put this code in `src/archive/mode.rs` and do validation before calling `buffer.pread_with::<&str>`.  Another way we could do the same stuff as `std::str::from_utf8` and `std::str::from_utf8_unchecked` for `pread_with::<&str>`.

I think, first way is more suitable. But also it would be great to put some docs for `pread_with::<&str>`, that raw data should be valid utf8 string.

**Comment by m4b** [comment]
Actually taking a second look here, I'm a little bit confused what the issue is? Specifically, scroll::Pread on an &str uses this implementation:

https://github.com/m4b/scroll/blob/73c1d6764446626593f19422021445c21183698e/src/ctx.rs#L699-L705

(i.e., it calls ::from_ut8 for you).

Could you attach your full stack trace? There shouldn't be any panicking at all here, since the error should be propagated down to the callee (and the unwrap shouldn't be a utf8 error unwrap in core str, since we rewrap that error in scroll to BadInput)

**Comment by nathaniel-daniel** [comment]
I think this is due to the line [here](https://github.com/m4b/goblin/blob/0.5.4/src/archive/mod.rs#L163) directly indexing into the name str without previously validating the byte indexes. In some cases, this could split a multibyte codepoint, so it wouldn't be able to return a str and panics instead. I think this line could be replaced with 
```rust
if name.len() > 3 && name.get(0..3) == Some("#1/") {
```
to work around the issue.

**Comment by m4b** [comment]
Ok sounds good let’s do it!
