### ISSUE TITLE
Internalize scroll::error::Error

### ISSUE THREAD

**Issue by endeav0r** [m4b/goblin#40]
When using goblin with error chains, if I want to match the error with things like `elf.dynstrtab.get()`, I need to handle the `scroll::error::Error` error. This would require me to also include the `scroll` crate.

It would be nice if this became a goblin error instead, so I don't need to explicitly include another crate to handle this error.

**Comment by m4b** [comment]
Hehe, yup this was an oversight on my part, and already noted in #33 :)

Most APIs a user would use are already fixed in master or 0.0.10. The remainder will be also purged by 0.0.11

Also speaking of `get`, its now an `Option<Result<&str>>` in master; sorry about the breaking API changes, fuzzing turned up some issues.  Hoping to nail down most of the API space by 1.0 (primarily by using it in projects and seeing what is painful and what sucks, etc.) then will follow semver.

Anyway, I'll be adding a a CHANGELOG to be a nicer citizen in the meantime

**Comment by endeav0r** [comment]
Thanks! Your doing great work with this library.

**Comment by m4b** [comment]
Thanks! :heart:
