### ISSUE TITLE
Parse ELF notes

### ISSUE THREAD

**Issue by willglynn** [m4b/goblin#49]
`greadelf` can produce data like:

```
Displaying notes found in: .note.ABI-tag
  Owner                 Data size	Description
  GNU                  0x00000010	NT_GNU_ABI_TAG (ABI version tag)
    OS: Linux, ABI: 2.6.24

Displaying notes found in: .note.gnu.build-id
  Owner                 Data size	Description
  GNU                  0x00000014	NT_GNU_BUILD_ID (unique build ID bitstring)
    Build ID: 42f22997b0796cdd2f49d3f3bd148081b8fe2845

Displaying notes found in: .note.gnu.gold-version
  Owner                 Data size	Description
  GNU                  0x00000009	NT_GNU_GOLD_VERSION (gold version)
    Version: gold 1.11
```

I want this data -- particularly `NT_GNU_BUILD_ID` -- for collating with external debugging data.

My understanding is that the linker (usually?) consolidates all the note sections into a single `PT_NOTE`  segment, and that the segment remains parseable even if the section headers are stripped.

I think the `PT_NOTE` segment is a series of target-endian structs like:

```rust
struct Note<'a> {
  namesz: u32,
  descsz: u32,
  type: u32,

  name: &'a [u8], // NUL terminated string, where `namesz` includes the terminator
  // padding such that namesz + padding % 4 == 0
  desc: &'a [u8], // arbitrary data of length `descsz`
  // padding such that descsz + padding % 4 == 0
}
```

The meaning of `type` depends on `name`, meaning that if I want to determine that value, I need to find a note having both `name == b"GNU\0"` and `type == NT_GNU_BUILD_ID == 3`.

**Comment by m4b** [comment]
Yea, let's add it (and the constants, etc.)!

I checked, if you `sstrip` a binary, readelf, etc., can reconstruct the `PT_NOTE` section because they all have the same struct format, so yes, you are correct.

but let's do it right and add the 32/64 bit variants from elf.h; your version, `Note<'a>` will be our synthesized version.  We can just drop the `namesz` and `descz` altogether, since they're encoded in the synthesized, attached data.

```c
/* Note section contents.  Each entry in the note section begins with
   a header of a fixed form.  */

typedef struct
{
  Elf32_Word n_namesz;			/* Length of the note's name.  */
  Elf32_Word n_descsz;			/* Length of the note's descriptor.  */
  Elf32_Word n_type;			/* Type of the note.  */
} Elf32_Nhdr;

typedef struct
{
  Elf64_Word n_namesz;			/* Length of the note's name.  */
  Elf64_Word n_descsz;			/* Length of the note's descriptor.  */
  Elf64_Word n_type;			/* Type of the note.  */
} Elf64_Nhdr;
```

I guess we can just add a `NoteIterator` to `ProgramHeader`? Dunno have to think of nicest way; suggestions welcome :)

**Comment by willglynn** [comment]
How does padding work on 64-bit ELF? Is it still `% 4 == 0`, or is it `% 8`?

**Comment by m4b** [comment]
> How does padding work on 64-bit ELF? Is it still % 4 == 0, or is it % 8?

@willglynn what specifically do you mean? I don't actually know much about padding offhand, @le-jzr probably does though.

But why do you ask, something to do with above struct defs, or?

**Comment by m4b** [comment]
the implementation currently is broken for 32-bit binaries :sob: pretty sure this is what @willglynn you were asking about

**Comment by le-jzr** [comment]
It's `% 8` on ELF64. http://www.sco.com/developers/gabi/latest/ch5.pheader.html#note_section

**Comment by le-jzr** [comment]
This just means you have to align the pointer to `desc` up to a multiple of 4 (ELF32) or 8 (ELF64).

**Comment by m4b** [comment]
This is completely ridiculous. ELF nonsense strikes again. Or rather mainline ELF compilers preserving bad behavior.

It looks like _both_ 32 and 64 bit ELF files use **32-bit structs**; the error was because I _accidentally_ parsed 32-bit forms for 64-bit, and 64-bit for 32 (and hence parsed out bad data): https://github.com/m4b/goblin/blob/8ac32549f6838871aeaff8f2fcb890bd12e76e03/src/elf/note.rs#L138-L139

You can also see this because the `PT_NOTE` alignment is 4:

```
  3     PT_NOTE           R       0x1c8     0x1c8       0x1c8       0x24      0x24      0x4       
```

I guess there's not much reason to use a 64-bit note struct but... then why is it an available struct?
